-- 1. Create Products Table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('frames', 'sunglasses')),
  gender TEXT NOT NULL CHECK (gender IN ('men', 'women', 'unisex')),
  image TEXT NOT NULL,
  description TEXT NOT NULL,
  specs JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create Orders Table
CREATE TABLE orders (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  shipping_address TEXT NOT NULL,
  total_amount NUMERIC NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create Order Items Table
-- This links products to a specific order so we can track quantities
CREATE TABLE order_items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id),
  quantity INTEGER NOT NULL,
  unit_price NUMERIC NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read products
CREATE POLICY "Allow public read access to products" ON products FOR SELECT USING (true);

-- Allow anyone to insert orders (since users checking out might not be logged in yet)
CREATE POLICY "Allow public to insert orders" ON orders FOR INSERT WITH CHECK (true);

-- Allow anyone to insert order items
CREATE POLICY "Allow public to insert order items" ON order_items FOR INSERT WITH CHECK (true);


-- ==========================================
-- INITIAL MOCK DATA (Seeding Products)
-- ==========================================

INSERT INTO products (id, name, price, category, gender, image, description, specs) VALUES
(1, 'Classic Aviator', 4500, 'frames', 'unisex', 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=400&h=400&fit=crop', 'Timeless aviator frames crafted with lightweight titanium for all-day comfort.', '[{"label": "Material", "value": "Titanium"}, {"label": "Weight", "value": "22g"}, {"label": "Lens Width", "value": "55mm"}, {"label": "Bridge", "value": "16mm"}]'::jsonb),
(2, 'Round Retro', 3800, 'frames', 'unisex', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&h=400&fit=crop', 'Vintage-inspired round frames with a modern twist for effortless style.', '[{"label": "Material", "value": "Acetate"}, {"label": "Weight", "value": "28g"}, {"label": "Lens Width", "value": "50mm"}, {"label": "Bridge", "value": "20mm"}]'::jsonb),
(3, 'Wayfarer Bold', 5200, 'sunglasses', 'men', 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop', 'Bold wayfarer sunglasses with UV400 protection and polarized lenses.', '[{"label": "Material", "value": "Acetate"}, {"label": "UV Protection", "value": "UV400"}, {"label": "Lens Width", "value": "54mm"}, {"label": "Polarized", "value": "Yes"}]'::jsonb),
(4, 'Square Elite', 6000, 'frames', 'men', 'https://images.unsplash.com/photo-1614715838608-dd527c46231d?w=400&h=400&fit=crop', 'Premium square frames with spring hinges for a perfect fit.', '[{"label": "Material", "value": "Stainless Steel"}, {"label": "Weight", "value": "25g"}, {"label": "Lens Width", "value": "52mm"}, {"label": "Bridge", "value": "18mm"}]'::jsonb),
(5, 'Cat Eye Luxe', 4800, 'sunglasses', 'women', 'https://images.unsplash.com/photo-1577803645773-f96470509666?w=400&h=400&fit=crop', 'Elegant cat-eye sunglasses with gradient lenses and gold accents.', '[{"label": "Material", "value": "Metal & Acetate"}, {"label": "UV Protection", "value": "UV400"}, {"label": "Lens Width", "value": "56mm"}, {"label": "Polarized", "value": "Yes"}]'::jsonb),
(6, 'Sport Shield', 5500, 'sunglasses', 'men', 'https://images.unsplash.com/photo-1508296695146-257a814070b4?w=400&h=400&fit=crop', 'Wraparound sport sunglasses designed for active lifestyles.', '[{"label": "Material", "value": "TR90 Nylon"}, {"label": "UV Protection", "value": "UV400"}, {"label": "Lens Width", "value": "68mm"}, {"label": "Polarized", "value": "Yes"}]'::jsonb),
(7, 'Rimless Feather', 7000, 'frames', 'women', 'https://images.unsplash.com/photo-1591076482161-42ce6da69f67?w=400&h=400&fit=crop', 'Ultra-lightweight rimless frames that feel invisible on your face.', '[{"label": "Material", "value": "Titanium"}, {"label": "Weight", "value": "15g"}, {"label": "Lens Width", "value": "53mm"}, {"label": "Bridge", "value": "17mm"}]'::jsonb),
(8, 'Oversized Glam', 5800, 'sunglasses', 'women', 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=400&h=400&fit=crop', 'Statement oversized sunglasses with full UV protection.', '[{"label": "Material", "value": "Acetate"}, {"label": "UV Protection", "value": "UV400"}, {"label": "Lens Width", "value": "62mm"}, {"label": "Polarized", "value": "No"}]'::jsonb),
(9, 'Classic Rectangle', 3500, 'frames', 'men', 'https://images.unsplash.com/photo-1614715838608-dd527c46231d?w=400&h=400&fit=crop', 'Smart rectangular frames for a professional look.', '[{"label": "Material", "value": "Metal"}, {"label": "Weight", "value": "24g"}, {"label": "Lens Width", "value": "54mm"}, {"label": "Bridge", "value": "18mm"}]'::jsonb),
(10, 'Round Crystal', 4200, 'frames', 'women', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&h=400&fit=crop', 'Chic transparent round frames with subtle detailing.', '[{"label": "Material", "value": "Acetate"}, {"label": "Weight", "value": "26g"}, {"label": "Lens Width", "value": "48mm"}, {"label": "Bridge", "value": "19mm"}]'::jsonb),
(11, 'Sport Wrap', 5400, 'sunglasses', 'men', 'https://images.unsplash.com/photo-1508296695146-257a814070b4?w=400&h=400&fit=crop', 'Performance wrap sunglasses for outdoor sports.', '[{"label": "Material", "value": "Polycarbonate"}, {"label": "UV Protection", "value": "UV400"}, {"label": "Lens Width", "value": "65mm"}, {"label": "Polarized", "value": "Yes"}]'::jsonb),
(12, 'Butterfly Elegance', 4900, 'sunglasses', 'women', 'https://images.unsplash.com/photo-1577803645773-f96470509666?w=400&h=400&fit=crop', 'Feminine butterfly sunglasses with a gradient tint.', '[{"label": "Material", "value": "Acetate"}, {"label": "UV Protection", "value": "UV400"}, {"label": "Lens Width", "value": "58mm"}, {"label": "Polarized", "value": "No"}]'::jsonb),
(13, 'Geometric Chic', 6500, 'frames', 'women', 'https://images.unsplash.com/photo-1591076482161-42ce6da69f67?w=400&h=400&fit=crop', 'Modern geometric frames that make a bold statement.', '[{"label": "Material", "value": "Titanium & Acetate"}, {"label": "Weight", "value": "20g"}, {"label": "Lens Width", "value": "54mm"}, {"label": "Bridge", "value": "17mm"}]'::jsonb),
(14, 'Everyday Essential', 3200, 'frames', 'men', 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=400&h=400&fit=crop', 'Durable everyday frames for reliable comfort and style.', '[{"label": "Material", "value": "TR90 Flex"}, {"label": "Weight", "value": "18g"}, {"label": "Lens Width", "value": "55mm"}, {"label": "Bridge", "value": "16mm"}]'::jsonb),
(15, 'Pilot Classic', 4100, 'sunglasses', 'men', 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop', 'Classic pilot teardrop shape with mirror lenses.', '[{"label": "Material", "value": "Metal Alloy"}, {"label": "UV Protection", "value": "UV400"}, {"label": "Lens Width", "value": "58mm"}, {"label": "Polarized", "value": "Yes"}]'::jsonb),
(16, 'Rose Gold Mirage', 5100, 'sunglasses', 'women', 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=400&h=400&fit=crop', 'Elegant rose gold frames with tinted gradient lenses.', '[{"label": "Material", "value": "Stainless Steel"}, {"label": "UV Protection", "value": "UV400"}, {"label": "Lens Width", "value": "55mm"}, {"label": "Polarized", "value": "No"}]'::jsonb),
(17, 'Tortoiseshell Classic', 3950, 'frames', 'unisex', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&h=400&fit=crop', 'Iconic tortoiseshell pattern for a vintage intellectual look.', '[{"label": "Material", "value": "Acetate"}, {"label": "Weight", "value": "26g"}, {"label": "Lens Width", "value": "51mm"}, {"label": "Bridge", "value": "19mm"}]'::jsonb),
(18, 'Browline Master', 4600, 'frames', 'men', 'https://images.unsplash.com/photo-1614715838608-dd527c46231d?w=400&h=400&fit=crop', 'Distinct browline frames combining retro and professional styles.', '[{"label": "Material", "value": "Metal & Acetate"}, {"label": "Weight", "value": "23g"}, {"label": "Lens Width", "value": "52mm"}, {"label": "Bridge", "value": "20mm"}]'::jsonb),
(19, 'Cat Eye Dazzle', 6200, 'frames', 'women', 'https://images.unsplash.com/photo-1591076482161-42ce6da69f67?w=400&h=400&fit=crop', 'Sharp cat eye profile embellished with subtle crystal details.', '[{"label": "Material", "value": "Premium Acetate"}, {"label": "Weight", "value": "28g"}, {"label": "Lens Width", "value": "53mm"}, {"label": "Bridge", "value": "16mm"}]'::jsonb),
(20, 'Hexagon Matrix', 5800, 'sunglasses', 'unisex', 'https://images.unsplash.com/photo-1577803645773-f96470509666?w=400&h=400&fit=crop', 'Unique hexagonal lenses with minimalist wire frames.', '[{"label": "Material", "value": "Titanium"}, {"label": "UV Protection", "value": "UV400"}, {"label": "Lens Width", "value": "50mm"}, {"label": "Polarized", "value": "Yes"}]'::jsonb),
(21, 'Oversized Shield', 7500, 'sunglasses', 'women', 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=400&h=400&fit=crop', 'Dramatic mask-style shield sunglasses for maximum coverage and style.', '[{"label": "Material", "value": "Polycarbonate"}, {"label": "UV Protection", "value": "UV400"}, {"label": "Lens Width", "value": "135mm"}, {"label": "Polarized", "value": "No"}]'::jsonb),
(22, 'Navigator Pro', 6800, 'sunglasses', 'men', 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop', 'Square navigator style shades with premium polarized coating.', '[{"label": "Material", "value": "Stainless Steel"}, {"label": "UV Protection", "value": "UV400"}, {"label": "Lens Width", "value": "57mm"}, {"label": "Polarized", "value": "Yes"}]'::jsonb);

-- ==========================================
-- 4. Create Admin Users Table
-- ==========================================
CREATE TABLE admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
);

-- Seed default admin user
INSERT INTO admin_users (email, password) VALUES ('admin@specswear.com', 'test123');

-- Enable RLS for admin_users
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;

-- Allow public read/update for client-side evaluation
CREATE POLICY "Allow public read admin_users" ON admin_users FOR SELECT USING (true);
CREATE POLICY "Allow public update admin_users" ON admin_users FOR UPDATE USING (true);
